[package]
name = "dog-button-server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simple_logger = "2"
kwap = "0.9"
rodio = {default-features=false, version = "0.15", features = ["symphonia-all"]}
